export const FETCH_PKMN_START = 'FETCH_PKMN_START';
export const FETCH_PKMN_SUCCESS = 'FETCH_PKMN_SUCCESS';
export const FETCH_PKMN_FAIL = 'FETCH_PKMN_FAILFETCH_PKMN_FAIL';
export const LOADING_POKEMONS = 'LOADING_POKEMONS';

export const CHANGE_GEN = 'CHANGE_GEN';

export const SET_CURRENT_PKMN = 'SET_CURRENT_PKMN';
export const FETCH_CURRENT_PKMN_START = 'FETCH_CURRENT_PKMN_START';
export const FETCH_CURRENT_PKMN_SUCCESS = 'FETCH_CURRENT_PKMN_SUCCESS';
export const FETCH_CURRENT_PKMN_FAIL = 'FETCH_CURRENT_PKMN_FAIL';
export const LOADING_CURRENT_PKMN = 'LOADING_CURRENT_PKMN';

export const FETCH_EVO_CHAIN = 'FETCH_EVO_CHAIN';
export const FETCH_EVO_CHAIN_START = 'FETCH_EVO_CHAIN_START';
export const FETCH_EVO_CHAIN_SUCCESS = 'FETCH_EVO_CHAIN_SUCCESS';
export const FETCH_EVO_CHAIN_FAIL = 'FETCH_EVO_CHAIN_FAIL';


export const ADD_TO_TEAM = 'ADD_TO_TEAM';
export const REMOVE_FROM_TEAM = 'REMOVE_FROM_TEAM';
