export const FETCH_PKMN_START = 'FETCH_PKMN_START';
export const FETCH_PKMN_SUCCESS = 'FETCH_PKMN_SUCCESS';
export const FETCH_PKMN_FAIL = 'FETCH_PKMN_FAILFETCH_PKMN_FAIL';

export const CHANGE_GEN = 'CHANGE_GEN';

export const SET_CURRENT_PKMN = 'SET_CURRENT_PKMN';
export const FETCH_CURRENT_PKMN_START = 'FETCH_CURRENT_PKMN_START';
export const FETCH_CURRENT_PKMN_SUCCESS = 'FETCH_CURRENT_PKMN_SUCCESS';
export const FETCH_CURRENT_PKMN_FAIL = 'FETCH_CURRENT_PKMN_FAIL';
