export const natures = [
    {name: "Adamant", inc: "attack", dec: "special-attack"},
    {name: "Bashful", inc: "none", dec: "none"},
    {name: "Bold", inc: "defense", dec: "attack"},
    {name: "Brave", inc: "attack", dec: "speed"},
    {name: "Calm", inc: "special-attack", dec: "attack"},
    {name: "Careful", inc: "special-defense", dec: "special-attack"},
    {name: "Docile", inc: "none", dec: "none"},
    {name: "Gentle", inc: "special-defense", dec: "defense"},
    {name: "Hardy", inc: "none", dec: "none"},
    {name: "Hasty", inc: "speed", dec: "defense"},
    {name: "Impish", inc: "defense", dec: "special-attack"},
    {name: "Jolly", inc: "speed", dec: "special-attack"},
    {name: "Lax", inc: "defense", dec: "special-defense"},
    {name: "Lonley", inc: "attack", dec: "defense"},
    {name: "Mild", inc: "special-attack", dec: "defense"},
    {name: "Modest", inc: "special-attack", dec: "attack"},
    {name: "Naive", inc: "speed", dec: "special-defense"},
    {name: "Naughty", inc: "attack", dec: "special-defense"},
    {name: "Quiet", inc: "special-attack", dec: "speed"},
    {name: "Quirky", inc: "none", dec: "none"},
    {name: "Rash", inc: "special-attack", dec: "special-defense"},
    {name: "Relaxed", inc: "defense", dec: "speed"},
    {name: "Sassy", inc: "special-defense", dec: "speed"},
    {name: "Serious", inc: "none", dec: "none"},
    {name: "Timid", inc: "speed", dec: "attack"},
]