export const natures = [
    {name: "Adamant", inc: "Attack", dec: "Sp. Atk"},
    {name: "Bashful", inc: "none", dec: "none"},
    {name: "Bold", inc: "Defense", dec: "Attack"},
    {name: "Brave", inc: "Attack", dec: "Speed"},
    {name: "Calm", inc: "Sp. Atk", dec: "Attack"},
    {name: "Careful", inc: "Sp. Def", dec: "Sp. Atk"},
    {name: "Docile", inc: "none", dec: "none"},
    {name: "Gentle", inc: "Sp. Def", dec: "Defense"},
    {name: "Hardy", inc: "none", dec: "none"},
    {name: "Hasty", inc: "Speed", dec: "Defense"},
    {name: "Impish", inc: "Defense", dec: "Sp. Atk"},
    {name: "Jolly", inc: "Speed", dec: "Sp. Atk"},
    {name: "Lax", inc: "Defense", dec: "Sp. Def"},
    {name: "Lonley", inc: "Attack", dec: "Defense"},
    {name: "Mild", inc: "Sp. Atk", dec: "Defense"},
    {name: "Modest", inc: "Sp. Atk", dec: "Attack"},
    {name: "Naive", inc: "Speed", dec: "Sp. Def"},
    {name: "Naughty", inc: "Attack", dec: "Sp. Def"},
    {name: "Quiet", inc: "Sp. Atk", dec: "Speed"},
    {name: "Quirky", inc: "none", dec: "none"},
    {name: "Rash", inc: "Sp. Atk", dec: "Sp. Def"},
    {name: "Relaxed", inc: "Defense", dec: "Speed"},
    {name: "Sassy", inc: "Sp. Def", dec: "Speed"},
    {name: "Serious", inc: "none", dec: "none"},
    {name: "Timid", inc: "Speed", dec: "Attack"},
]